apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define resources that are part of this Kustomization
resources:
  - merchant-website-prod.yaml

images:
  - name: hephaestus.apollo.com.ph:5000/payment-gateway-v2/merchant-website
    newTag: 1.0.0-prod
